// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_6AoXHyaBmmlH3OlSFQbrLKns2XDhVLk',
    appId: '1:374432394724:web:af7667d0f87379a7d42bf1',
    messagingSenderId: '374432394724',
    projectId: 'ic-flutter-2c6c3',
    authDomain: 'ic-flutter-2c6c3.firebaseapp.com',
    storageBucket: 'ic-flutter-2c6c3.firebasestorage.app',
    measurementId: 'G-0EX427SWZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWpFBO87nkgXH60VfUrxIoPkhJ61qbxE4',
    appId: '1:374432394724:android:3bc83f128dfea4bbd42bf1',
    messagingSenderId: '374432394724',
    projectId: 'ic-flutter-2c6c3',
    storageBucket: 'ic-flutter-2c6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmQQyoUvREswfpvocVRUe5Hy7KPfcLok',
    appId: '1:374432394724:ios:cbe5d8f68e67c9d1d42bf1',
    messagingSenderId: '374432394724',
    projectId: 'ic-flutter-2c6c3',
    storageBucket: 'ic-flutter-2c6c3.firebasestorage.app',
    iosClientId: '374432394724-glp4ev4baissegtk4j3nr0nh675b6t7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagerFirebase',
  );
}
